version: "3"
name: "vhm-tools"
services:
  notification_service:
    image: 102205/tools-notification-service:1.0
    container_name: notification_service-tools
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - vhm-tools

networks:
  vhm-tools:
    name: vhm-tools-nw
    external: true
