version: "3"
name: "vhm-tools"
services:
  postgres:
    image: postgres:14
    ports:
      - 2340:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'vhm-tools']
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: vhm-tools
      POSTGRES_PASSWORD: vhm-tools
      POSTGRES_DB: vhm-tools
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - vhm_tools

  redis:
    image: redis
    ports:
      - 9730:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 30s
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - vhm_tools

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - .docker-data/rabbitmq/data/:/var/lib/rabbitmq/
      - .docker-data/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - vhm_tools

networks:
  vhm_tools:
    driver: bridge

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

